package com.MyFarmerApp.MyFarmer.ai.models;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class NluResult {
    private IntentType intent;
    
    // For temporal queries (e.g., "last 7 days")
    private LocalDate startDate;
    private LocalDate endDate;
    private Integer month; // 1-12
    private Integer year;
    
    // For categorical data queries
    private Boolean isDayWise;    // e.g., "day wise breakdown"
    private String targetEntity;  // e.g., "labour_name" for labour queries
    
    // Explicit NLU extraction slots
    private String comparisonTarget;  // e.g., "last_month"
    private String verificationReference; 
    private String reportMode;        // "summary" or "detailed"

    private String detectedLanguage; // e.g., EN, HI, HINGLISH
    
    // Follow-up & Resolution Tracking
    private Boolean isFollowUp;      // True if the query relies on previous context
    private Boolean needsClarification; // True if intent is ambiguous and system should halt
    private String clarificationMessage; // The question to ask the user, generated by NLU
    
    // Raw query for fallback to Global Knowledge
    private String rawQuery;
}
